---
cluster_name: frs-cluster
cluster_domain: kdx.local

cluster_nodes:
  - name: sds-frs-n01
    fqdn: sds-frs-n01.kdx.local
    public_ip: 192.168.88.118
    corosync_ip: 172.12.2.84
    iscsi_ip: 172.22.2.35
    vmware_plug: sds-frs-n01
  - name: sds-frs-n02
    fqdn: sds-frs-n02.kdx.local
    public_ip: 192.168.88.119
    corosync_ip: 172.12.2.85
    iscsi_ip: 172.22.2.36
    vmware_plug: sds-frs-n02

public_interface: ens34
corosync_interface: ens35
iscsi_interface: ens36

vip_resource_name: vip
vip_address: 192.168.88.120
vip_cidr_netmask: 24
resource_group_enabled: true
resource_group_name: frs-sds-group

truenas_iscsi_portal: 172.22.2.33
truenas_iscsi_port: 3260
iscsi_target_iqn: iqn.2005-10.org.freenas.ctl:frs-share
zfs_disk_by_id: /dev/disk/by-id/scsi-STrueNAS_iSCSI_Disk_64118f6612f5dc5
zfs_pool_name: frs_pool
zfs_ashift: 14
zfs_zvols:
  - name: testlun
    size: 50G

cluster_stonith_enabled: true
cluster_no_quorum_policy: ignore
cluster_resource_stickiness: 100
run_failover_test: false
failover_test_node: sds-frs-n01

vmware_fencing:
  enabled: true
  agent: fence_vmware_rest
  vcenter: 192.168.88.59
  username: bozturk@gmlab.local
  password: "{{ vault_vmware_fencing_password }}"
  ssl_insecure: true
  power_timeout: 60
  shell_timeout: 10
  login_timeout: 10
  pcmk_host_check: static-list

hacluster_password: "{{ vault_hacluster_password }}"

rhel_repositories:
  - rhel-8-for-x86_64-baseos-rpms
  - rhel-8-for-x86_64-appstream-rpms
  - codeready-builder-for-rhel-8-x86_64-rpms
  - rhel-8-for-x86_64-highavailability-rpms

epel_release_url: https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
zfs_release_url: https://zfsonlinux.org/epel/zfs-release-2-3.el8.noarch.rpm

cluster_packages:
  - kernel
  - kernel-core
  - kernel-devel
  - kernel-headers
  - kernel-modules
  - kernel-modules-extra
  - gcc
  - make
  - dkms
  - zfs
  - iscsi-initiator-utils
  - device-mapper-multipath
  - pcs
  - pacemaker
  - corosync
  - resource-agents
  - fence-agents-all
