---
- name: Configure cluster properties
  hosts: ha_cluster
  become: true
  tasks:
    - name: Read cluster properties
      ansible.builtin.command: pcs property config
      register: pcs_property_config
      changed_when: false
      run_once: true

    - name: Read cluster resource defaults
      ansible.builtin.command: pcs resource defaults config
      register: pcs_resource_defaults
      changed_when: false
      failed_when: false
      run_once: true

    - name: Configure STONITH property
      ansible.builtin.command: "pcs property set stonith-enabled={{ cluster_stonith_enabled | ternary('true', 'false') }}"
      run_once: true
      when: "pcs_property_config.stdout is not regex('stonith-enabled[:=]\\s*' ~ (cluster_stonith_enabled | ternary('true', 'false')))"

    - name: Configure no-quorum-policy
      ansible.builtin.command: "pcs property set no-quorum-policy={{ cluster_no_quorum_policy }}"
      run_once: true
      when: "pcs_property_config.stdout is not regex('no-quorum-policy[:=]\\s*' ~ cluster_no_quorum_policy)"

    - name: Configure default resource stickiness
      ansible.builtin.command: "pcs resource defaults update resource-stickiness={{ cluster_resource_stickiness }}"
      run_once: true
      when: "pcs_resource_defaults.stdout is not regex('resource-stickiness[:=]\\s*' ~ (cluster_resource_stickiness | string))"
