---
cluster_name: frs-cluster
cluster_domain: kdx.local

cluster_nodes:
  - name: frs-sds-n1
    fqdn: frs-sds-n1.kdx.local
    public_ip: 172.12.2.77
    corosync_ip: 10.10.10.77
    iscsi_ip: 10.20.20.77
    vmware_plug: frs-sds-n1
  - name: frs-sds-n2
    fqdn: frs-sds-n2.kdx.local
    public_ip: 172.12.2.78
    corosync_ip: 10.10.10.78
    iscsi_ip: 10.20.20.78
    vmware_plug: frs-sds-n2

public_interface: ens192
corosync_interface: ens224
iscsi_interface: ens256

vip_resource_name: vip
vip_address: 172.12.2.100
vip_cidr_netmask: 24

truenas_iscsi_portal: 10.20.20.75
truenas_iscsi_port: 3260
iscsi_target_iqn: iqn.2005-10.org.freenas.ctl:frs-share
zfs_disk_by_id: /dev/disk/by-id/scsi-STrueNAS_iSCSI_Disk_64118f6612f5dc5
zfs_pool_name: frs_pool
zfs_ashift: 14
zfs_zvols:
  - name: testlun
    size: 50G

cluster_stonith_enabled: true
cluster_no_quorum_policy: ignore
cluster_resource_stickiness: 100

vmware_fencing:
  enabled: true
  agent: fence_vmware_rest
  vcenter: vcsa.kdx.local
  username: svc_pacemaker_fence@vsphere.local
  password: "{{ vault_vmware_fencing_password }}"
  ssl_insecure: true
  action: reboot
  power_timeout: 60
  shell_timeout: 10
  login_timeout: 10
  pcmk_host_check: static-list

hacluster_password: "{{ vault_hacluster_password }}"

rhel_repositories:
  - rhel-8-for-x86_64-baseos-rpms
  - rhel-8-for-x86_64-appstream-rpms
  - codeready-builder-for-rhel-8-x86_64-rpms
  - rhel-8-for-x86_64-highavailability-rpms

cluster_packages:
  - kernel-devel
  - kernel-headers
  - gcc
  - make
  - dkms
  - zfs
  - iscsi-initiator-utils
  - device-mapper-multipath
  - pcs
  - pacemaker
  - corosync
  - resource-agents
  - fence-agents-all

